version: '3'

services: 
  notebook:
    build: .
    command: jupyter notebook --ip 0.0.0.0 --port 9999 --allow-root
    ports: 
      - 9999:9999
    volumes: 
      - .:/work
    working_dir: /work